import jsPDF from "jspdf";
import type { Prediction } from "./api";

export function generateReportPdf(pred: Prediction, patientName: string) {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const w = doc.internal.pageSize.getWidth();

  // Header band
  doc.setFillColor(37, 99, 235);
  doc.rect(0, 0, w, 80, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold").setFontSize(20).text("NeuroSense AI", 40, 42);
  doc.setFont("helvetica", "normal").setFontSize(11).text("Epilepsy Detection · Medical Report", 40, 60);

  doc.setTextColor(20, 30, 55);
  doc.setFont("helvetica", "bold").setFontSize(14).text("Patient Information", 40, 120);
  doc.setFont("helvetica", "normal").setFontSize(11);
  const info = [
    ["Patient", patientName],
    ["Report ID", pred.id],
    ["Date", new Date(pred.createdAt).toLocaleString()],
    ["Channels", String(pred.channels)],
    ["Duration", `${pred.durationSec} seconds`],
  ];
  info.forEach(([k, v], i) => {
    doc.setTextColor(120, 130, 150).text(k, 40, 148 + i * 20);
    doc.setTextColor(20, 30, 55).text(v, 160, 148 + i * 20);
  });

  // Prediction block
  doc.setDrawColor(220, 228, 240);
  doc.roundedRect(40, 270, w - 80, 110, 8, 8);
  doc.setFont("helvetica", "bold").setFontSize(13).setTextColor(20, 30, 55).text("AI Prediction", 56, 296);
  doc.setFontSize(28).setTextColor(pred.label === "Seizure" ? 220 : 30, pred.label === "Seizure" ? 60 : 130, 60)
    .text(pred.label, 56, 340);
  doc.setFont("helvetica", "normal").setFontSize(11).setTextColor(90, 100, 120)
    .text(`Confidence: ${(pred.confidence * 100).toFixed(1)}%`, 56, 362);

  // Waveform sketch
  doc.setFont("helvetica", "bold").setFontSize(13).setTextColor(20, 30, 55).text("EEG Waveform (excerpt)", 40, 420);
  const x0 = 40, y0 = 490, ww = w - 80, hh = 80;
  doc.setDrawColor(230, 234, 244).roundedRect(x0, y0 - hh, ww, hh, 6, 6);
  doc.setDrawColor(37, 99, 235);
  const step = ww / pred.waveform.length;
  for (let i = 1; i < pred.waveform.length; i++) {
    const x1 = x0 + (i - 1) * step, x2 = x0 + i * step;
    const y1 = y0 - hh / 2 - pred.waveform[i - 1].v * (hh / 3);
    const y2 = y0 - hh / 2 - pred.waveform[i].v * (hh / 3);
    doc.line(x1, y1, x2, y2);
  }

  // Remarks
  doc.setFont("helvetica", "bold").setFontSize(13).setTextColor(20, 30, 55).text("Clinical Remarks", 40, 540);
  doc.setFont("helvetica", "normal").setFontSize(11).setTextColor(70, 80, 100);
  const remarks = pred.remarks || "Awaiting physician review. This AI-generated prediction should be validated by a qualified neurologist.";
  doc.text(doc.splitTextToSize(remarks, w - 80), 40, 560);

  // Footer
  doc.setFontSize(9).setTextColor(140, 150, 170)
    .text("Generated by NeuroSense AI · Not a substitute for professional medical advice.", 40, 800);

  doc.save(`neurosense-report-${pred.id}.pdf`);
}