import { createFileRoute } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { api } from "@/lib/api";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { EegWave } from "@/components/eeg-wave";
import { generateReportPdf } from "@/lib/pdf";
import { useAuth } from "@/lib/auth";
import { Download, Printer } from "lucide-react";

export const Route = createFileRoute("/patient/reports")({
  head: () => ({ meta: [{ title: "Reports — NeuroSense" }] }),
  component: ReportsPage,
});

function ReportsPage() {
  const { user } = useAuth();
  const { data = [] } = useQuery({ queryKey: ["reports"], queryFn: () => api.listPredictions("p-001") });
  const latest = data[0];

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between flex-wrap gap-3">
        <div>
          <h1 className="text-2xl font-semibold tracking-tight">Medical Reports</h1>
          <p className="text-sm text-muted-foreground mt-1">Clinical-grade reports of your EEG analyses.</p>
        </div>
        {latest && <Button onClick={() => generateReportPdf(latest, user?.name || "Patient")}><Download className="h-4 w-4 mr-2" />Download latest</Button>}
      </div>

      {latest && (
        <Card className="p-8 bg-card shadow-[var(--shadow-card)] print:shadow-none">
          <div className="flex items-start justify-between border-b border-border pb-6">
            <div>
              <div className="text-xs uppercase tracking-[0.2em] text-primary">NeuroSense AI · Clinical Report</div>
              <h2 className="mt-2 text-2xl font-semibold">Electroencephalography Analysis</h2>
              <div className="mt-1 text-sm text-muted-foreground">Report ID: <span className="font-mono">{latest.id}</span></div>
            </div>
            <Button variant="outline" size="sm" onClick={() => window.print()}><Printer className="h-4 w-4 mr-2" />Print</Button>
          </div>

          <div className="grid sm:grid-cols-3 gap-6 py-6 border-b border-border text-sm">
            <div><div className="text-xs text-muted-foreground uppercase tracking-wider">Patient</div><div className="mt-1 font-medium">{user?.name || "Patient"}</div></div>
            <div><div className="text-xs text-muted-foreground uppercase tracking-wider">Date</div><div className="mt-1 font-medium">{new Date(latest.createdAt).toLocaleString()}</div></div>
            <div><div className="text-xs text-muted-foreground uppercase tracking-wider">Recording</div><div className="mt-1 font-medium">{latest.channels} ch · {latest.durationSec}s</div></div>
          </div>

          <div className="py-6 border-b border-border">
            <div className="text-xs text-muted-foreground uppercase tracking-wider">Impression</div>
            <div className={`mt-2 text-3xl font-bold ${latest.label === "Seizure" ? "text-destructive" : latest.label === "Pre-ictal" ? "text-warning" : "text-success"}`}>
              {latest.label}
            </div>
            <div className="mt-1 text-sm text-muted-foreground">Model confidence <span className="font-semibold text-foreground">{(latest.confidence*100).toFixed(1)}%</span></div>
          </div>

          <div className="py-6 border-b border-border">
            <div className="text-xs text-muted-foreground uppercase tracking-wider mb-3">EEG waveform (excerpt)</div>
            <EegWave data={latest.waveform} height={200} color={latest.label === "Seizure" ? "oklch(0.60 0.24 25)" : "oklch(0.55 0.20 250)"} />
          </div>

          <div className="py-6">
            <div className="text-xs text-muted-foreground uppercase tracking-wider mb-2">Clinical remarks</div>
            <p className="text-sm leading-relaxed">{latest.remarks || "Awaiting physician review. This AI-generated prediction should be validated by a qualified neurologist before any clinical decision."}</p>
          </div>

          <div className="pt-6 border-t border-border text-xs text-muted-foreground">
            Generated by NeuroSense AI · Model v3.2 · Not a substitute for professional medical advice.
          </div>
        </Card>
      )}

      <div>
        <h2 className="text-base font-semibold mb-3">All reports</h2>
        <Card className="divide-y divide-border">
          {data.map((p) => (
            <div key={p.id} className="p-4 flex items-center gap-4">
              <Badge variant={p.label === "Seizure" ? "destructive" : "secondary"}>{p.label}</Badge>
              <div className="flex-1"><div className="text-sm font-medium">Report {p.id}</div><div className="text-xs text-muted-foreground">{new Date(p.createdAt).toLocaleString()}</div></div>
              <div className="text-xs hidden sm:block">Conf. <span className="font-semibold">{(p.confidence*100).toFixed(0)}%</span></div>
              <Button variant="ghost" size="sm" onClick={() => generateReportPdf(p, user?.name || "Patient")}><Download className="h-4 w-4" /></Button>
            </div>
          ))}
        </Card>
      </div>
    </div>
  );
}