/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PatientRouteImport } from './routes/patient'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DoctorRouteImport } from './routes/doctor'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PatientIndexRouteImport } from './routes/patient.index'
import { Route as PatientUploadRouteImport } from './routes/patient.upload'
import { Route as PatientReportsRouteImport } from './routes/patient.reports'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientRoute = PatientRouteImport.update({
  id: '/patient',
  path: '/patient',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorRoute = DoctorRouteImport.update({
  id: '/doctor',
  path: '/doctor',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientIndexRoute = PatientIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PatientRoute,
} as any)
const PatientUploadRoute = PatientUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => PatientRoute,
} as any)
const PatientReportsRoute = PatientReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => PatientRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/doctor': typeof DoctorRoute
  '/login': typeof LoginRoute
  '/patient': typeof PatientRouteWithChildren
  '/register': typeof RegisterRoute
  '/patient/reports': typeof PatientReportsRoute
  '/patient/upload': typeof PatientUploadRoute
  '/patient/': typeof PatientIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/doctor': typeof DoctorRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/patient/reports': typeof PatientReportsRoute
  '/patient/upload': typeof PatientUploadRoute
  '/patient': typeof PatientIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/doctor': typeof DoctorRoute
  '/login': typeof LoginRoute
  '/patient': typeof PatientRouteWithChildren
  '/register': typeof RegisterRoute
  '/patient/reports': typeof PatientReportsRoute
  '/patient/upload': typeof PatientUploadRoute
  '/patient/': typeof PatientIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/doctor'
    | '/login'
    | '/patient'
    | '/register'
    | '/patient/reports'
    | '/patient/upload'
    | '/patient/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/doctor'
    | '/login'
    | '/register'
    | '/patient/reports'
    | '/patient/upload'
    | '/patient'
  id:
    | '__root__'
    | '/'
    | '/doctor'
    | '/login'
    | '/patient'
    | '/register'
    | '/patient/reports'
    | '/patient/upload'
    | '/patient/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DoctorRoute: typeof DoctorRoute
  LoginRoute: typeof LoginRoute
  PatientRoute: typeof PatientRouteWithChildren
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient': {
      id: '/patient'
      path: '/patient'
      fullPath: '/patient'
      preLoaderRoute: typeof PatientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor': {
      id: '/doctor'
      path: '/doctor'
      fullPath: '/doctor'
      preLoaderRoute: typeof DoctorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/': {
      id: '/patient/'
      path: '/'
      fullPath: '/patient/'
      preLoaderRoute: typeof PatientIndexRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/upload': {
      id: '/patient/upload'
      path: '/upload'
      fullPath: '/patient/upload'
      preLoaderRoute: typeof PatientUploadRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/reports': {
      id: '/patient/reports'
      path: '/reports'
      fullPath: '/patient/reports'
      preLoaderRoute: typeof PatientReportsRouteImport
      parentRoute: typeof PatientRoute
    }
  }
}

interface PatientRouteChildren {
  PatientReportsRoute: typeof PatientReportsRoute
  PatientUploadRoute: typeof PatientUploadRoute
  PatientIndexRoute: typeof PatientIndexRoute
}

const PatientRouteChildren: PatientRouteChildren = {
  PatientReportsRoute: PatientReportsRoute,
  PatientUploadRoute: PatientUploadRoute,
  PatientIndexRoute: PatientIndexRoute,
}

const PatientRouteWithChildren =
  PatientRoute._addFileChildren(PatientRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DoctorRoute: DoctorRoute,
  LoginRoute: LoginRoute,
  PatientRoute: PatientRouteWithChildren,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
