/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PatientRouteImport } from './routes/patient'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DoctorRouteImport } from './routes/doctor'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PatientIndexRouteImport } from './routes/patient.index'
import { Route as DoctorIndexRouteImport } from './routes/doctor.index'
import { Route as PatientUploadRouteImport } from './routes/patient.upload'
import { Route as PatientSettingsRouteImport } from './routes/patient.settings'
import { Route as PatientReportsRouteImport } from './routes/patient.reports'
import { Route as PatientHistoryRouteImport } from './routes/patient.history'
import { Route as DoctorPatientsRouteImport } from './routes/doctor.patients'
import { Route as DoctorAnalyticsRouteImport } from './routes/doctor.analytics'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientRoute = PatientRouteImport.update({
  id: '/patient',
  path: '/patient',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorRoute = DoctorRouteImport.update({
  id: '/doctor',
  path: '/doctor',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientIndexRoute = PatientIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PatientRoute,
} as any)
const DoctorIndexRoute = DoctorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DoctorRoute,
} as any)
const PatientUploadRoute = PatientUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => PatientRoute,
} as any)
const PatientSettingsRoute = PatientSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => PatientRoute,
} as any)
const PatientReportsRoute = PatientReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => PatientRoute,
} as any)
const PatientHistoryRoute = PatientHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => PatientRoute,
} as any)
const DoctorPatientsRoute = DoctorPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => DoctorRoute,
} as any)
const DoctorAnalyticsRoute = DoctorAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DoctorRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/doctor': typeof DoctorRouteWithChildren
  '/login': typeof LoginRoute
  '/patient': typeof PatientRouteWithChildren
  '/register': typeof RegisterRoute
  '/doctor/analytics': typeof DoctorAnalyticsRoute
  '/doctor/patients': typeof DoctorPatientsRoute
  '/patient/history': typeof PatientHistoryRoute
  '/patient/reports': typeof PatientReportsRoute
  '/patient/settings': typeof PatientSettingsRoute
  '/patient/upload': typeof PatientUploadRoute
  '/doctor/': typeof DoctorIndexRoute
  '/patient/': typeof PatientIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/doctor/analytics': typeof DoctorAnalyticsRoute
  '/doctor/patients': typeof DoctorPatientsRoute
  '/patient/history': typeof PatientHistoryRoute
  '/patient/reports': typeof PatientReportsRoute
  '/patient/settings': typeof PatientSettingsRoute
  '/patient/upload': typeof PatientUploadRoute
  '/doctor': typeof DoctorIndexRoute
  '/patient': typeof PatientIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/doctor': typeof DoctorRouteWithChildren
  '/login': typeof LoginRoute
  '/patient': typeof PatientRouteWithChildren
  '/register': typeof RegisterRoute
  '/doctor/analytics': typeof DoctorAnalyticsRoute
  '/doctor/patients': typeof DoctorPatientsRoute
  '/patient/history': typeof PatientHistoryRoute
  '/patient/reports': typeof PatientReportsRoute
  '/patient/settings': typeof PatientSettingsRoute
  '/patient/upload': typeof PatientUploadRoute
  '/doctor/': typeof DoctorIndexRoute
  '/patient/': typeof PatientIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/doctor'
    | '/login'
    | '/patient'
    | '/register'
    | '/doctor/analytics'
    | '/doctor/patients'
    | '/patient/history'
    | '/patient/reports'
    | '/patient/settings'
    | '/patient/upload'
    | '/doctor/'
    | '/patient/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/doctor/analytics'
    | '/doctor/patients'
    | '/patient/history'
    | '/patient/reports'
    | '/patient/settings'
    | '/patient/upload'
    | '/doctor'
    | '/patient'
  id:
    | '__root__'
    | '/'
    | '/doctor'
    | '/login'
    | '/patient'
    | '/register'
    | '/doctor/analytics'
    | '/doctor/patients'
    | '/patient/history'
    | '/patient/reports'
    | '/patient/settings'
    | '/patient/upload'
    | '/doctor/'
    | '/patient/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DoctorRoute: typeof DoctorRouteWithChildren
  LoginRoute: typeof LoginRoute
  PatientRoute: typeof PatientRouteWithChildren
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient': {
      id: '/patient'
      path: '/patient'
      fullPath: '/patient'
      preLoaderRoute: typeof PatientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor': {
      id: '/doctor'
      path: '/doctor'
      fullPath: '/doctor'
      preLoaderRoute: typeof DoctorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/': {
      id: '/patient/'
      path: '/'
      fullPath: '/patient/'
      preLoaderRoute: typeof PatientIndexRouteImport
      parentRoute: typeof PatientRoute
    }
    '/doctor/': {
      id: '/doctor/'
      path: '/'
      fullPath: '/doctor/'
      preLoaderRoute: typeof DoctorIndexRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/patient/upload': {
      id: '/patient/upload'
      path: '/upload'
      fullPath: '/patient/upload'
      preLoaderRoute: typeof PatientUploadRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/settings': {
      id: '/patient/settings'
      path: '/settings'
      fullPath: '/patient/settings'
      preLoaderRoute: typeof PatientSettingsRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/reports': {
      id: '/patient/reports'
      path: '/reports'
      fullPath: '/patient/reports'
      preLoaderRoute: typeof PatientReportsRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/history': {
      id: '/patient/history'
      path: '/history'
      fullPath: '/patient/history'
      preLoaderRoute: typeof PatientHistoryRouteImport
      parentRoute: typeof PatientRoute
    }
    '/doctor/patients': {
      id: '/doctor/patients'
      path: '/patients'
      fullPath: '/doctor/patients'
      preLoaderRoute: typeof DoctorPatientsRouteImport
      parentRoute: typeof DoctorRoute
    }
    '/doctor/analytics': {
      id: '/doctor/analytics'
      path: '/analytics'
      fullPath: '/doctor/analytics'
      preLoaderRoute: typeof DoctorAnalyticsRouteImport
      parentRoute: typeof DoctorRoute
    }
  }
}

interface DoctorRouteChildren {
  DoctorAnalyticsRoute: typeof DoctorAnalyticsRoute
  DoctorPatientsRoute: typeof DoctorPatientsRoute
  DoctorIndexRoute: typeof DoctorIndexRoute
}

const DoctorRouteChildren: DoctorRouteChildren = {
  DoctorAnalyticsRoute: DoctorAnalyticsRoute,
  DoctorPatientsRoute: DoctorPatientsRoute,
  DoctorIndexRoute: DoctorIndexRoute,
}

const DoctorRouteWithChildren =
  DoctorRoute._addFileChildren(DoctorRouteChildren)

interface PatientRouteChildren {
  PatientHistoryRoute: typeof PatientHistoryRoute
  PatientReportsRoute: typeof PatientReportsRoute
  PatientSettingsRoute: typeof PatientSettingsRoute
  PatientUploadRoute: typeof PatientUploadRoute
  PatientIndexRoute: typeof PatientIndexRoute
}

const PatientRouteChildren: PatientRouteChildren = {
  PatientHistoryRoute: PatientHistoryRoute,
  PatientReportsRoute: PatientReportsRoute,
  PatientSettingsRoute: PatientSettingsRoute,
  PatientUploadRoute: PatientUploadRoute,
  PatientIndexRoute: PatientIndexRoute,
}

const PatientRouteWithChildren =
  PatientRoute._addFileChildren(PatientRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DoctorRoute: DoctorRouteWithChildren,
  LoginRoute: LoginRoute,
  PatientRoute: PatientRouteWithChildren,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
